version: "3.8"

services:
  be:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: be
    ports:
      - "5001:5001"
    environment:
      - DOTNET_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5001
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: messengerdb
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: appMessenger
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
