version: "3.8"

services:
  webapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: be
    platform: linux/amd64
    ports:
      - "5001:5001"
    environment:
      - DOTNET_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5001
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: messengerdb_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: messengerdb
    ports:
      - "5431:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
